/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.sql.SQLException;
import customexceptions.InvalidDateException;
import db.TasksDB;
import java.awt.Color;
import java.awt.Component;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import model.Priority;
import model.Status;
import model.Task;

/**
 *
 * @author samtheradiant
 */
public class CreateTask extends javax.swing.JDialog {

    TasksScreen obj;
    
    /**
     * Creates new form CreateTask
     */
    public CreateTask(java.awt.Frame parent, boolean modal, TasksScreen obj) {
        super(parent, modal);
        this.obj = obj;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        priorityComBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        statusComBox = new javax.swing.JComboBox<>();
        startDateLbl = new javax.swing.JLabel();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        //startDateChooser.setDateFormatString("dd-MM-yyyy");

        //for (Component c : startDateChooser.getComponents()) {
            //    ((JComponent) c).setBackground(new Color(40, 40, 39));
            //}

        // JComponent editorUI = startDateChooser.getDateEditor().getUiComponent();
        // editorUI.setForeground(new Color(221, 255, 255));
        endDateChooser = new com.toedter.calendar.JDateChooser();
        // endDateChooser.setDateFormatString("dd-mm-yyyy");

        //
        //for (Component c : endDateChooser.getComponents()) {
            //    ((JComponent) c).setBackground(new Color(40, 40, 39));
            //}
        endDateLbl = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        descTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(21, 25, 34));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 34));

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(221, 255, 255));
        jLabel1.setText("Description:");

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(221, 255, 255));
        jLabel2.setText("Priority:");

        priorityComBox.setBackground(new java.awt.Color(40, 40, 39));
        priorityComBox.setForeground(new java.awt.Color(221, 255, 255));
        priorityComBox.setModel(new DefaultComboBoxModel<>(Priority.values()));

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(221, 255, 255));
        jLabel3.setText("Status:");

        statusComBox.setBackground(new java.awt.Color(40, 40, 39));
        statusComBox.setForeground(new java.awt.Color(221, 255, 255));
        statusComBox.setModel(new DefaultComboBoxModel<>(Status.values()));

        startDateLbl.setFont(new java.awt.Font("Myriad Pro", 0, 15)); // NOI18N
        startDateLbl.setForeground(new java.awt.Color(221, 255, 255));
        startDateLbl.setText("Start Date:");

        startDateChooser.setBackground(new java.awt.Color(40, 40, 39));
        startDateChooser.setForeground(new java.awt.Color(221, 255, 255));
        startDateChooser.setDateFormatString("yyyy-MM-dd");

        endDateChooser.setBackground(new java.awt.Color(40, 40, 39));
        endDateChooser.setDateFormatString("yyyy-MM-dd");

        endDateLbl.setFont(new java.awt.Font("Myriad Pro", 0, 15)); // NOI18N
        endDateLbl.setForeground(new java.awt.Color(221, 255, 255));
        endDateLbl.setText("End Date:");

        okButton.setBackground(new java.awt.Color(45, 168, 216));
        okButton.setForeground(new java.awt.Color(21, 25, 34));
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(45, 168, 216));
        cancelBtn.setForeground(new java.awt.Color(21, 25, 34));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        descTextField.setBackground(new java.awt.Color(40, 40, 39));
        descTextField.setForeground(new java.awt.Color(221, 255, 255));
        descTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priorityComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priorityComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(startDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(endDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelBtn))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
//        String title = descTextArea.getText();
//        if (title.isEmpty()) {
//            title = "Untitled";
//        }
        String desc = descTextField.getText();
        LocalDate startDate = LocalDate.ofInstant(startDateChooser.getDate().toInstant(), ZoneId.systemDefault());
        // Set start date to current date if user leaves the field empty
        if (startDate == null) {
            startDate = LocalDate.now();
        }
        LocalDate endDate = null;
        try {
            endDate = LocalDate.ofInstant(endDateChooser.getDate().toInstant(), ZoneId.systemDefault());
            if (!(startDate.compareTo(endDate) < 0)) {
                throw new InvalidDateException("End Date cannot be before than Start Date.");
            }
        } catch (InvalidDateException invD) {
            JOptionPane.showMessageDialog(rootPane, invD.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Status taskStatus = Status.getEnum(statusComBox.getSelectedItem().toString());
        Priority taskPriority = Priority.getEnum(priorityComBox.getSelectedItem().toString());
        Task task;
        if (endDate != null) {
            task = new Task(desc, taskStatus, startDate, endDate, taskPriority, obj.getProjectID());
        } else {
            task = new Task(desc, taskStatus, startDate, taskPriority, obj.getProjectID());
        }
        try {
            TasksDB.save(task);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error: Could not save to database.", JOptionPane.ERROR_MESSAGE);
            return;
        }
        obj.refreshTable();
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void descTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField descTextField;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private javax.swing.JLabel endDateLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<Priority> priorityComBox;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JLabel startDateLbl;
    private javax.swing.JComboBox<Status> statusComBox;
    // End of variables declaration//GEN-END:variables
}
