/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import customexceptions.FailureException;
import db.ProjectsDB;
import javax.swing.JOptionPane;
import model.Account;

/**
 *
 * @author samtheradiant
 */
public class DashboardScreen extends javax.swing.JPanel {

    /**
     * Creates new form DashboardScreen
     */
    public DashboardScreen() {
        initComponents();
        try {
            completdProjctsSpinner.setValue(ProjectsDB.getProjectCompletion());
            lblError.setText(""); //this will empty the error label if something was written in it previously
            
        } catch (FailureException ex) {
            //JOptionPane.showConfirmDialog(this, ex.getMessage());
            lblError.setText(ex.getMessage()); //this will show error
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        spinnerPanel = new javax.swing.JPanel();
        completdProjctsSpinner = new raven.spinner.SpinnerProgress();
        completedTaskSpinner = new raven.spinner.SpinnerProgress();
        spinnerProgress1 = new raven.spinner.SpinnerProgress();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(21, 25, 34));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(21, 25, 34));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 50));

        lblError.setForeground(new java.awt.Color(237, 60, 63));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setBackground(new java.awt.Color(21, 25, 34));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 420));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(21, 25, 34));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 420));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.EAST);

        upperPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(21, 25, 34));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 320));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        upperPanel.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(21, 25, 34));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 320));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        upperPanel.add(jPanel4, java.awt.BorderLayout.EAST);

        spinnerPanel.setBackground(new java.awt.Color(21, 25, 34));
        spinnerPanel.setPreferredSize(new java.awt.Dimension(742, 320));
        spinnerPanel.setLayout(new java.awt.BorderLayout());

        completdProjctsSpinner.setValue(25);
        completdProjctsSpinner.setPreferredSize(new java.awt.Dimension(200, 200));
        completdProjctsSpinner.setStringPainted(true);
        spinnerPanel.add(completdProjctsSpinner, java.awt.BorderLayout.EAST);

        completedTaskSpinner.setValue(50);
        completedTaskSpinner.setMaximumSize(new java.awt.Dimension(200, 200));
        completedTaskSpinner.setMinimumSize(new java.awt.Dimension(200, 200));
        completedTaskSpinner.setPreferredSize(new java.awt.Dimension(200, 200));
        completedTaskSpinner.setStringPainted(true);
        spinnerPanel.add(completedTaskSpinner, java.awt.BorderLayout.CENTER);

        spinnerProgress1.setPreferredSize(new java.awt.Dimension(200, 200));
        spinnerProgress1.setStringPainted(true);
        spinnerPanel.add(spinnerProgress1, java.awt.BorderLayout.LINE_START);

        upperPanel.add(spinnerPanel, java.awt.BorderLayout.CENTER);

        add(upperPanel, java.awt.BorderLayout.NORTH);

        jTable1.setBackground(new java.awt.Color(21, 25, 34));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title Of Project", "Number Of Task", "Completed Tasks", "Completion Percentage"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(45, 168, 216));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.spinner.SpinnerProgress completdProjctsSpinner;
    private raven.spinner.SpinnerProgress completedTaskSpinner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblError;
    private javax.swing.JPanel spinnerPanel;
    private raven.spinner.SpinnerProgress spinnerProgress1;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
