/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import customexceptions.FailureException;
import db.ProjectsDB;
import db.TasksDB;
import helper.CurrentSession;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.Account;
import model.DashboardData;

/**
 *
 * @author samtheradiant
 */
public class DashboardScreen extends javax.swing.JPanel {

    /**
     * Creates new form DashboardScreen
     */
    public DashboardScreen() {
        initComponents();
        
        JTableHeader tableHeader = tableMain.getTableHeader();
        tableHeader.setBackground(new Color(45,168,216));
        tableHeader.setForeground(new Color(21,25,34));
        
        try {
            completdProjctsSpinner.setValue(ProjectsDB.getProjectCompletion());
            lblError.setText(""); //this will empty the error label if something was written in it previously
            
        } catch (FailureException ex) {
            //JOptionPane.showConfirmDialog(this, ex.getMessage());
            lblError.setText(ex.getMessage()); //this will show error
        }
        
        populateTable();
    }
    
    //Method to populate table
    public void populateTable(){
        lblError.setText("");
        DefaultTableModel model = (DefaultTableModel)tableMain.getModel();
        //delete all existing rows
        model.setRowCount(0);

        ArrayList<DashboardData> projects = null;
        try{
            projects = TasksDB.getDashboardData();
            for (DashboardData project : projects){
                model.addRow(new Object[]{project.getTitle(), project.getTotalTasks(), project.getDoneTasks(),project.getPercentage()});
            }
        }catch (FailureException fe){
            lblError.setText(fe.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        spinnerPanel = new javax.swing.JPanel();
        projectsSpinnerPanel = new javax.swing.JPanel();
        completdProjctsSpinner = new raven.spinner.SpinnerProgress();
        jLabel2 = new javax.swing.JLabel();
        tasksSpinnerPanel = new javax.swing.JPanel();
        completedTaskSpinner = new raven.spinner.SpinnerProgress();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMain = new javax.swing.JTable();

        setBackground(new java.awt.Color(21, 25, 34));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(21, 25, 34));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 50));

        lblError.setForeground(new java.awt.Color(237, 60, 63));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setBackground(new java.awt.Color(21, 25, 34));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 420));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(21, 25, 34));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 420));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.EAST);

        upperPanel.setPreferredSize(new java.awt.Dimension(1000, 320));
        upperPanel.setLayout(new java.awt.BorderLayout());

        spinnerPanel.setBackground(new java.awt.Color(21, 25, 34));
        spinnerPanel.setMaximumSize(new java.awt.Dimension(742, 320));
        spinnerPanel.setMinimumSize(new java.awt.Dimension(742, 320));
        spinnerPanel.setPreferredSize(new java.awt.Dimension(742, 320));
        spinnerPanel.setLayout(new java.awt.BorderLayout());

        projectsSpinnerPanel.setBackground(new java.awt.Color(21, 25, 34));
        projectsSpinnerPanel.setMaximumSize(new java.awt.Dimension(250, 32767));
        projectsSpinnerPanel.setPreferredSize(new java.awt.Dimension(250, 320));

        completdProjctsSpinner.setValue(25);
        completdProjctsSpinner.setPreferredSize(new java.awt.Dimension(200, 200));
        completdProjctsSpinner.setStringPainted(true);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 135, 200));
        jLabel2.setText("Completed Projects");

        javax.swing.GroupLayout projectsSpinnerPanelLayout = new javax.swing.GroupLayout(projectsSpinnerPanel);
        projectsSpinnerPanel.setLayout(projectsSpinnerPanelLayout);
        projectsSpinnerPanelLayout.setHorizontalGroup(
            projectsSpinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectsSpinnerPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(projectsSpinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectsSpinnerPanelLayout.createSequentialGroup()
                        .addComponent(completdProjctsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectsSpinnerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45))))
        );
        projectsSpinnerPanelLayout.setVerticalGroup(
            projectsSpinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectsSpinnerPanelLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(completdProjctsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(26, 26, 26))
        );

        spinnerPanel.add(projectsSpinnerPanel, java.awt.BorderLayout.WEST);

        tasksSpinnerPanel.setBackground(new java.awt.Color(21, 25, 34));
        tasksSpinnerPanel.setMaximumSize(new java.awt.Dimension(250, 320));
        tasksSpinnerPanel.setPreferredSize(new java.awt.Dimension(250, 320));

        completedTaskSpinner.setValue(50);
        completedTaskSpinner.setMaximumSize(new java.awt.Dimension(200, 200));
        completedTaskSpinner.setMinimumSize(new java.awt.Dimension(200, 200));
        completedTaskSpinner.setPreferredSize(new java.awt.Dimension(200, 200));
        completedTaskSpinner.setStringPainted(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 135, 200));
        jLabel1.setText("Completed Tasks");

        javax.swing.GroupLayout tasksSpinnerPanelLayout = new javax.swing.GroupLayout(tasksSpinnerPanel);
        tasksSpinnerPanel.setLayout(tasksSpinnerPanelLayout);
        tasksSpinnerPanelLayout.setHorizontalGroup(
            tasksSpinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksSpinnerPanelLayout.createSequentialGroup()
                .addGroup(tasksSpinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tasksSpinnerPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(completedTaskSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tasksSpinnerPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        tasksSpinnerPanelLayout.setVerticalGroup(
            tasksSpinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tasksSpinnerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(completedTaskSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        spinnerPanel.add(tasksSpinnerPanel, java.awt.BorderLayout.CENTER);

        upperPanel.add(spinnerPanel, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(21, 25, 34));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 420));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        upperPanel.add(jPanel4, java.awt.BorderLayout.EAST);

        jPanel5.setBackground(new java.awt.Color(21, 25, 34));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 420));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        upperPanel.add(jPanel5, java.awt.BorderLayout.WEST);

        add(upperPanel, java.awt.BorderLayout.NORTH);

        tableMain.setBackground(new java.awt.Color(21, 25, 34));
        tableMain.setForeground(new java.awt.Color(221, 255, 255));
        tableMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title Of Project", "Number Of Task", "Completed Tasks", "Completion Percentage"
            }
        ));
        tableMain.setGridColor(new java.awt.Color(221, 255, 255));
        tableMain.setShowGrid(true);
        jScrollPane1.setViewportView(tableMain);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private raven.spinner.SpinnerProgress completdProjctsSpinner;
    private raven.spinner.SpinnerProgress completedTaskSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JPanel projectsSpinnerPanel;
    private javax.swing.JPanel spinnerPanel;
    private javax.swing.JTable tableMain;
    private javax.swing.JPanel tasksSpinnerPanel;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
