/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatDarculaLaf;
import javax.swing.UIManager;

/**
 *
 * @author samtheradiant
 */
public class ProjectAndTasks extends javax.swing.JPanel {

    /**
     * Creates new form ProjectAndTasks
     */
    public ProjectAndTasks() {
        try {
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectsScreen1 = new gui.ProjectsScreen();
        tasksScreen1 = new gui.TasksScreen();

        setLayout(new java.awt.CardLayout());
        add(projectsScreen1, "projectsCard");
        add(tasksScreen1, "tasksCard");
    }// </editor-fold>//GEN-END:initComponents

    public TasksScreen getTasksScreen() {
        return tasksScreen1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.ProjectsScreen projectsScreen1;
    private gui.TasksScreen tasksScreen1;
    // End of variables declaration//GEN-END:variables
}
